### ISSUE TITLE
Error 11852 - can it be more user friendly - IOS testing

### ISSUE THREAD

**Issue by srivadi** [CoVital-Project/covital_calibration_app#23]
When camera is disabled in settings and the user tries to use the camera to record, you get this error, Error 11852, Cannot use back camera and similarly for the front camera. Can it be more user friendly, to say Camera is off under settings.

**Comment by MalcolmMielle** [comment]
@vcapilladeveloper do you have any idea where that bug might be coming from?

**Comment by vcapilladeveloper** [comment]
Is that better?
![IMG_0026](https://user-images.githubusercontent.com/36862920/78826845-81794680-79e2-11ea-961c-73f4b38dc923.jpg)

**Comment by srivadi** [comment]
Yes. Thank you! :)
