### ISSUE TITLE
Tamara's text tweaks on latest version

### ISSUE THREAD

**Issue by TamaraAdlin** [CoVital-Project/covital_calibration_app#26]
Home:

Change to 
Thank you for providing data that will help us create CoVital, which will allow patients to self-monitor oxygen saturation and heart rate.

Please use this calibration tool to gather and submit the data we need to make CoVital accurate.

note this is an important adjustment. current text is confusing and makes it seem like THIS app is CoVital, and it isn't.  All of this text should appear before the instructions.

**Comment by TamaraAdlin** [comment]
Coundown page: Change "Cover camera pad with finger" to "Cover camera with finger pad."

measure using oximeter

Change 
Measure from finger pulse oximeter
To
Enter data from finger pulse oximeter


5 of 5 should have an edit option as well as submit. Edit button should be styled as a secondary button (not white on blue, use a blue font on a white background--see my previous wireframes.) link should take user back to the finger pulse oximeter page.

**Comment by MalcolmMielle** [comment]
Do you want me to remove the last sentence after the instructions also?

![Screenshot_20200410-115104](https://user-images.githubusercontent.com/4457840/78982060-99a3af80-7b21-11ea-903f-8fccef51df8b.png)

I've added an edit button like this:

![Screenshot_20200410-115210](https://user-images.githubusercontent.com/4457840/78982142-c061e600-7b21-11ea-877c-eb7e4d94e1bc.png)
