### ISSUE TITLE
Patient information, the keyboard on device covers the button Next:Patient History

### ISSUE THREAD

**Issue by srivadi** [CoVital-Project/covital_calibration_app#30]
When you enter the values on Patient information screen, when you start inputting the information, it covers the button, "Next:Patient History". Even scrolling through the window does not give that information. The done button is missing in this window. The only way is to go back to the previous screen and then come to this screen, then it shows the Next:Patient History button.

**Comment by MalcolmMielle** [comment]
The button should accessible if you close the keyboard. Is it a lb to do that?

**Comment by srivadi** [comment]
Unable to close the keyboard. There is no "done" button like the previous screen. The behavior is on the iphone. I would think the behavior maybe the same for android as well?

**Comment by MalcolmMielle** [comment]
@srivadi Sorry I haven't seen that update :/. On android, the behavior is expected, it's really easy to close the keyboard. Can you send a screenshot so we can see what is the exact problem?

@vcapilladeveloper is your last PR fixing this issue? On Android you have to remove the keyboard.

**Comment by MalcolmMielle** [comment]
Can you swipe down the keyboard to access the button?

**Comment by srivadi** [comment]
![Screen Shot 2020-04-12 at 6 32 05 PM](https://user-images.githubusercontent.com/60080919/79168132-f7443000-7d9d-11ea-8c33-4ec458519f77.png)

**Comment by srivadi** [comment]
You can see the screen shot, unable to exit out of the window.

**Comment by srivadi** [comment]
No, the keyboard does not move.

**Comment by MalcolmMielle** [comment]
The user can now dismiss the keyboard
