### ISSUE TITLE
No way to confirm when a submit is successful

### ISSUE THREAD

**Issue by srivadi** [CoVital-Project/covital_calibration_app#33]
The submit sometimes takes a long time to accomplish. There is no way to confirm if a submit was successful. A confirm window after submit is successful should be the expected behavior.

**Comment by MalcolmMielle** [comment]
There is a success page after the upload if the users waits for the uploads to complete. Once the user clicks on the submit button, a loading bar starts and then, once it's done, the confirm page is shown.

Here are the three states:

![Screenshot_20200411-211700](https://user-images.githubusercontent.com/4457840/79148789-659ce880-7dc6-11ea-9111-4250b9ba53be.png)

![Screenshot_20200411-211708](https://user-images.githubusercontent.com/4457840/79148790-66ce1580-7dc6-11ea-9da3-16a9799775b4.png)

![Screenshot_20200411-211750](https://user-images.githubusercontent.com/4457840/79148801-6a619c80-7dc6-11ea-8f9c-851e860ca764.png)
