### ISSUE TITLE
App does not send submit info

### ISSUE THREAD

**Issue by jorgelaranjo** [CoVital-Project/covital_calibration_app#36]
Scenario steps:
```
Open app, do reading, submit. Exit
Open app, do reading, submit. Exit.
Open app, do reading, submit... nothing happens.
```
Is there how to report bug from APP to collect APP logs?

**Comment by MalcolmMielle** [comment]
Which version of the app are you using? Only the latest version can upload to the server so if you are using one of the version prior the yesterday's update. it won't work.

**Comment by jorgelaranjo** [comment]
May well be that case. Is it possible then to output version on the home screen perhaps?
This version did UPLOAD at some point

**Comment by MalcolmMielle** [comment]
Yep it used to work. Sadly I realised too late that having the version number would be useful so it's not I'm yet. If I need to compile a new version I'll add that :p
