### ISSUE TITLE
Whislt submiting it is not clear it is doing it.

### ISSUE THREAD

**Issue by jorgelaranjo** [CoVital-Project/covital_calibration_app#37]
When submitting a reading it is not clear that it is happening.
The submission is on a notification and not on the app main screen itself.
At first sight it is almost as if the app is not doing anything [it is doing it on background it seems].

**Comment by MalcolmMielle** [comment]
It is in the foreground also. The title changes to "Submitting..." and there is a loading bar at the bottom of the screen that shows how long is left before the uploading is done. However, the user is free to quit this page manually if he wishes to.


![Screenshot_20200411-211708](https://user-images.githubusercontent.com/4457840/79241136-ef09f480-7e72-11ea-8281-d35d4e405f83.png)

**Comment by jorgelaranjo** [comment]
I may be using an older version then I suspect
